from datetime import timedelta, datetime

import ics
import requests
from django.http import HttpResponse
from rest_framework.status import HTTP_201_CREATED

from .models import Event


# import holidays into events
def ics_import(country, user):
    url = f"https://www.officeholidays.com/ics/ics_country.php?tbl_country={country}"
    c = ics.Calendar(requests.get(url).text)
    event_list = []
    for event in list(c.timeline):
        event_list.append(Event(name=event.name,
                                description=event.description,
                                date_begin=event.begin.datetime - timedelta(hours=3),
                                date_end=event.end.datetime - timedelta(hours=3),
                                date_remind=event.begin.datetime - timedelta(days=1) - timedelta(hours=3),
                                user=user))
    event_list = Event.objects.bulk_create(event_list)
    return True


# static list scraped from the website
country_list = [
    "afghanistan",
    "albania",
    "algeria",
    "american-samoa",
    "andorra",
    "angola",
    "anguilla",
    "antigua-and-barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bonaire-st-eustatius-saba",
    "bosnia-and-herzegovina",
    "botswana",
    "brazil",
    "british-virgin-islands",
    "brunei",
    "bulgaria",
    "burkina-faso",
    "burundi",
    "cambodia",
    "cameroon",
    "canada",
    "cape-verde",
    "cayman-islands",
    "central-african-republic",
    "chad",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo",
    "cook-islands",
    "costa-rica",
    "croatia",
    "cuba",
    "curacao",
    "cyprus",
    "czech-republic",
    "denmark",
    "djibouti",
    "dominica",
    "dominican-republic",
    "dr-congo",
    "east-timor",
    "ecuador",
    "egypt",
    "el-salvador",
    "equatorial-guinea",
    "eritrea",
    "estonia",
    "swaziland",
    "ethiopia",
    "Falkland-islands",
    "faroe-islands",
    "fiji",
    "finland",
    "france",
    "french-guiana",
    "french-polynesia",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guadeloupe",
    "guam",
    "guatemala",
    "guernsey",
    "guinea",
    "guinea-bissau",
    "guyana",
    "haiti",
    "honduras",
    "hong-kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle-of-man",
    "israel",
    "italy",
    "ivory-coast",
    "jamaica",
    "japan",
    "jersey",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "kosovo",
    "kuwait",
    "kyrgyzstan",
    "lao",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macau",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "martinique",
    "mauritania",
    "mauritius",
    "mexico",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nepal",
    "netherlands",
    "new-caledonia",
    "new-zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "north-korea",
    "macedonia",
    "norway",
    "oman",
    "pakistan",
    "palestine",
    "panama",
    "papua-new-guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "puerto-rico",
    "qatar",
    "romania",
    "russia",
    "rwanda",
    "saint-barthelemy",
    "saint-kitts-and-nevis",
    "saint-lucia",
    "saint-martin",
    "saint-vincent-and-the-grenadines",
    "samoa",
    "san-marino",
    "sao-tome-and-principe",
    "saudi-arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra-leone",
    "singapore",
    "sint-maarten",
    "slovakia",
    "slovenia",
    "solomon-islands",
    "somalia",
    "south-africa",
    "south-korea",
    "south-sudan",
    "spain",
    "sri-lanka",
    "sudan",
    "suriname",
    "sweden",
    "<ahref=",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "togo",
    "tonga",
    "trinidad-and-tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "turks-and-caicos-islands",
    "tuvalu",
    "uganda",
    "ukraine",
    "uae",
    "united-kingdom",
    "uruguay",
    "us-virgin-islands",
    "usa",
    "uzbekistan",
    "vanuatu",
    "vatican-city",
    "venezuela",
    "vietnam",
    "wallis-and-futuna",
    "yemen",
    "zambia",
    "zimbabwe"
]
